spring:
  datasource:
    url: jdbc:mysql://thunderclap.cn:9527/z_job?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    jpa:
        database: MySQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        hibernate:
          ddl-auto: update
    hikari:
      connection-test-query: SELECT 1