server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://xxxooo.com:8888/test?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    type: com.zaxxer.hikari.HikariDataSource
    jpa:
        database: MySQL
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
        show-sql: true
        hibernate:
          ddl-auto: update
    hikari:
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DatebookHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1

  # 发送邮箱配置
  mail:
    # QQ邮箱主机
    host: smtp.qq.com
    # 用户名
    username: xxx@ooo.com
    # QQ邮箱开启SMTP的授权码
    password: zzzzzzzzzzzzzzzzzzzzzzzz

